config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :tasks
  resources :boards
  resources :workspaces
  devise_for :members
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :member_workspaces
  has_many :members, through: :member_workspaces
  has_many :boards
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :set_workspace, only: %i[ show edit update destroy ]

  # GET /workspaces or /workspaces.json
  def index
    @workspaces = Workspace.all
  end

  # GET /workspaces/1 or /workspaces/1.json
  def show
  end

  # GET /workspaces/new
  def new
    @workspace = Workspace.new
  end

  # GET /workspaces/1/edit
  def edit
  end

  # POST /workspaces or /workspaces.json
  def create
    @workspace = Workspace.new(workspace_params)

    respond_to do |format|
      if @workspace.save
        format.html { redirect_to workspace_url(@workspace), notice: "Workspace was successfully created." }
        format.json { render :show, status: :created, location: @workspace }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workspaces/1 or /workspaces/1.json
  def update
    respond_to do |format|
      if @workspace.update(workspace_params)
        format.html { redirect_to workspace_url(@workspace), notice: "Workspace was successfully updated." }
        format.json { render :show, status: :ok, location: @workspace }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workspace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workspaces/1 or /workspaces/1.json
  def destroy
    @workspace.destroy

    respond_to do |format|
      format.html { redirect_to workspaces_url, notice: "Workspace was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workspace
      @workspace = Workspace.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workspace_params
      params.require(:workspace).permit(:name)
    end
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/workspaces/_form.html.haml
= form_for @workspace do |f|
  - if @workspace.errors.any?
    #error_explanation
      %h2= "#{pluralize(@workspace.errors.count, "error")} prohibited this workspace from being saved:"
      %ul
        - @workspace.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/workspaces/edit.html.haml
%h1 Editing workspace

= render 'form'

= link_to 'Show', @workspace
\|
= link_to 'Back', workspaces_path

app/views/workspaces/index.html.haml
%h1 Listing workspaces

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @workspaces.each do |workspace|
      %tr
        %td= workspace.name
        %td= link_to 'Show', workspace
        %td= link_to 'Edit', edit_workspace_path(workspace)
        %td= link_to 'Destroy', workspace, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Workspace', new_workspace_path

app/views/workspaces/new.html.haml
%h1 New workspace

= render 'form'

= link_to 'Back', workspaces_path

app/views/workspaces/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @workspace.name

= link_to 'Edit', edit_workspace_path(@workspace)
\|
= link_to 'Back', workspaces_path