config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :tasks
  resources :boards
  resources :workspaces
  devise_for :members
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :workspace
  has_many :tasks
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:name, :workspace_id)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  - if @board.errors.any?
    #error_explanation
      %h2= "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
      %ul
        - @board.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :workspace
    = f.text_field :workspace
  .actions
    = f.submit 'Save'

app/views/boards/edit.html.haml
%h1 Editing board

= render 'form'

= link_to 'Show', @board
\|
= link_to 'Back', boards_path

app/views/boards/index.html.haml
%h1 Listing boards

%table
  %thead
    %tr
      %th Name
      %th Workspace
      %th
      %th
      %th

  %tbody
    - @boards.each do |board|
      %tr
        %td= board.name
        %td= board.workspace
        %td= link_to 'Show', board
        %td= link_to 'Edit', edit_board_path(board)
        %td= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Board', new_board_path

app/views/boards/new.html.haml
%h1 New board

= render 'form'

= link_to 'Back', boards_path

app/views/boards/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @board.name
%p
  %b Workspace:
  = @board.workspace

= link_to 'Edit', edit_board_path(@board)
\|
= link_to 'Back', boards_path